# permissions for end users to edit podinfoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: podinfo-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: angi-takehome
    app.kubernetes.io/part-of: angi-takehome
    app.kubernetes.io/managed-by: kustomize
  name: podinfo-editor-role
rules:
- apiGroups:
  - app.podinfo.angi.takehome
  resources:
  - podinfoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.podinfo.angi.takehome
  resources:
  - podinfoes/status
  verbs:
  - get
